name: tf-metal
channels:
- defaults
- conda-forge
dependencies:
- python=3.9 ## specify desired version
- pip
- pandas
- matplotlib
- scikit-learn
- altair
- tensorflow

## PyPI packages
- pip:
  # - tensorflow
  - skforecast
  - streamlit
  - streamlib
