name: CPSC325-Project
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.2.1
  - autopep8=2.0.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=39.0.2
  - cycler=0.11.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - executing=1.2.0
  - fonttools=4.39.2
  - freetype=2.12.1
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - ipykernel=6.22.0
  - ipython=8.11.0
  - jedi=0.18.2
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=15.0.7
  - libdeflate=1.17
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=16.0.0
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.1.0
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.1.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.7.1
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.28.2
  - setuptools=67.6.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zstd=1.5.2
