name: tf-metal
channels:
  - apple
  - conda-forge
dependencies:
  - altair
  - finta
  - ipykernel
  - matplotlib
  - pandas
  - pip
  - python=3.9 ## specify desired version
  - scikit-learn
  - streamlit
  - tensorflow-deps

  ## PyPI packages
  - pip:
      - skforecast
      - tensorflow-macos
      - tensorflow-metal ## optional, but recommended
