name: tf-metal
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9 ## specify desired version
  - pip
  - tensorflow-deps
  - ipykernel
  - matplotlib
  - pandas
  - scikit-learn
  - finta

  ## PyPI packages
  - pip:
      - tensorflow-macos
      - tensorflow-metal ## optional, but recommended
      - skforecast
